language: node_js
node_js:
- 14
install:
- npm install
services:
- postgresql
env:
  global:
  - PGPORT=5432
  - PGUSER=postgres
  - PGPASSWORD=postgres
  - PGHOST=localhost
  - PGDATABASE=postgres
before_script:
- psql -c "CREATE TABLE Customer (id INTEGER PRIMARY KEY, name VARCHAR NOT NULL, email VARCHAR NOT NULL);" -U postgres
- psql -c "INSERT INTO Customer (id, email, name) VALUES (1, 'boonji@gmail.com', 'Boon Ji');" -U postgres
- psql -c "INSERT INTO Customer (id, email, name) VALUES (2, 'peterparker@gmail.com', 'Peter Parker');" -U postgres
- psql -c "INSERT INTO Customer (id, email, name) VALUES (3, 'tonystark@gmail.com', 'Tony Stark');" -U postgres
- psql -c "SELECT * from Customer;" -U postgres
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: sB952jCiG4i1aLkcuLgiAUFHp2TORwG62wG/FLdpgBU/47s63XP5J2o1KTil6EbQwb4EkTIjdjIkumlPf7VkH+pNW4Rm3J4vkJXAKq+VfoXDnW9kQjqM7mN/A4oehXsArTrGDquPWU4lVo5mgo0BcljNGyBSoHeA0yNmXCIcHSNHDFg6xwSZU9Ks70QQW/TBvnWcChDziitrFCdDRH60nYZeLCCZt2KSJRiFnJ8Fe6OA7YR1sAY3zM9NCAGdWK/QDurottKVvTqKbnIqwJ2S84YUGxuToN+BvY+XDGmiEkmJJLRTF/SQiPbGTz+VnIDo2zq+bPj1263hHBQexw+X5cZYKJZXvr/VV+jcVH8UvA20JUdTS4RVRW28A4fInTO8PB2g2rud0S34T8kCprF1vLVPvd0MwjClUkYWxPu0gp0rwLZdvl2iWZXZefsG0mCRbRz7GZAjmkgc+GJNNJoEW8NgcTd1cdGaHQ92Dx3lqxKSRywo8cuwEfTA4o58Dk9TOW1b1I1jGYy2R5ikOk2vDEr/g35MuO/TExr7s6XArLB/rldNaEIQHM4fokMthuMc4j6TvbSG2+vqlrMou/JuI12ouVacv0ePQv2anQd7tBsda5qLMQ0ptS/xmt41jkeaUz4UszG5TpiaX8XyENT1RK+zNzLCh8bp99YJ/T9NxXE=
  app: tanboonji-cs3219-otot-taskb
  on:
    branch: main
