language: node_js
node_js:
- 14
install:
- npm install
services:
- postgresql
env:
  global:
  - PGPORT=5432
  - PGUSER=postgres
  - PGPASSWORD=postgres
  - PGHOST=localhost
  - PGDATABASE=postgres

before_script:
- psql -c "CREATE TABLE Customer (id INTEGER PRIMARY KEY, name VARCHAR NOT NULL, email VARCHAR NOT NULL);" -U postgres
- psql -c "INSERT INTO Customer (id, email, name) VALUES (1, 'boonji@gmail.com', 'Boon Ji');" -U postgres
- psql -c "INSERT INTO Customer (id, email, name) VALUES (2, 'peterparker@gmail.com', 'Peter Parker');" -U postgres
- psql -c "INSERT INTO Customer (id, email, name) VALUES (3, 'tonystark@gmail.com', 'Tony Stark');" -U postgres
- psql -c "SELECT * from Customer;" -U postgres

script:
- npm test

deploy:
  provider: heroku
  api_key:
    secure: LWFIXPvd7z7HLeo8hRTpPFIn9NUs96mSjcMQY5f2J+Ll4oDscR66MqWjx0I9sOiLl5XWlOQBYc+OL36eybNYbULGeXAzrYcQdRn48IA9WZODmtIEnhVzFek9yMkrXtAxAYAPYdr5ECPpxYGAzhTaYciQC5KJbOm7MN9NsoXGKDrCYdwD2rHkNWXH6R6wQlzKCMHowArNnN1J3fDWegX0CZebSRE90x6bbxS5udsgG8Gps3zrTAXH9TaiT6WeuhjcZXYnDEEGRT6WCZWxNJ67FAVKkpd2e5Tg3VY9AcEVsefiM2Uz4t8LzHaTZygLKoomYARWb10EksKuemxGS/AnfnQjpqktN3JinBY9ZfY84jsUWaK9GyF4vXIBC1ihM5Rr5SezxcMwfpAVOG+rnUy5u+g7Eu245EP6LbNl8xo4qaJiTv4bL59SU8O42JsdgTdWV2EVIkBaDaEnnvlJI14AXCfywStbzJHa0QS819D/F+9WFqLGRVNLn9vRz+uvQuuiEM0wX98Cls+shYnzXPAgMFHGLpy/TVQGF4ton6+/hFXFh8tqDeaiz1nKRsufoQQOv2Fp3JNAysazcUYdcn6pKep/gb9pSqPnd1+0xuhhSD9HJHlG3sQfP7rQZwNXfX69linw9f3ywSLDnpCIlpwBRQYOu3D0TTtayz5aNlUyfA4=
  app: tanboonji-cs3219-otot-taskb
  on:
    branch: main