language: node_js
node_js:
- 14
install:
- npm install
services:
- postgresql
env:
  global:
  - PGPORT=5432
  - PGUSER=postgres
  - PGPASSWORD=postgres
  - PGHOST=localhost
  - PGDATABASE=postgres
before_script:
- psql -c "CREATE TABLE Customer (id INTEGER PRIMARY KEY, name VARCHAR NOT NULL, email VARCHAR NOT NULL);" -U postgres
- psql -c "INSERT INTO Customer (id, email, name) VALUES (1, 'boonji@gmail.com', 'Boon Ji');" -U postgres
- psql -c "INSERT INTO Customer (id, email, name) VALUES (2, 'peterparker@gmail.com', 'Peter Parker');" -U postgres
- psql -c "INSERT INTO Customer (id, email, name) VALUES (3, 'tonystark@gmail.com', 'Tony Stark');" -U postgres
- psql -c "SELECT * from Customer;" -U postgres
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: sUEDJXeWmkkdP6BH4tARYSNEPfnwNd4VjYUy439BXBAwYDnrb5Qw7NSExIsMr3nqf8Z6BBCP8BDxBVkugbBHPug5lS5kvlsNuvjBEvd13B9HJ9u7d3LPHW2REOB3pObEuIQd+vQPdnqHjWIjvrrkiNjEUKZKadvqn+2JyU3PfN0cTyn/rjYSU+0E42ci4xP9F1TyDfbstuKJKs72uOrU1/yNVLz6L4NIRsZV8ngJBOvdVYxv8KL9ORZ+ts+OelCLB4E4W2eUVKoLL6fgcWZeeNqSalYwl4YsjoooTBRBIBwlhpiXMu4abbTdW8q+yJ0S2EMXcib3pYMEMS417cfS5NaqmrL1xGJ8FUsfZ9SFXynLP00TyLdvhizXGkfzvCBddc52nZkzsJsWQ5TW39m8qQUMtN8vL8OOAKCL6obKZa+ovY5P/ZAY3kmO9f6hThcwAnqt3JHHBy6kJBNZgZQX8FEIhE1rkJefRx2fBrLRDoz4HarTsPYlZYblVeuWxmp+xPkUrFIffsv6oZUj9nm+K4ODVKqSbvus4hMBBT8cI46i09aRdU3jH36k9SpJ7mOr1euzJ7c33ZhyLbOZXN1rerOYpPIWgGDD6vHj++7n/gfnUi8PnAz57qJhMLlu6sRMSEjf4yus9jmxrQTMTPn87fCU3TH+ukszcc8tYTXK224=
  app: tanboonji-otot-taskb
  on:
    branch: main
